export const SET_ACTIVE_PATH = "SET_ACTIVE_PATH";
export const SET_IS_ACTIVE_PATH_DIRECTORY = "SET_IS_ACTIVE_PATH_DIRECTORY";
export const SET_WORKSPACE = "SET_WORKSPACE";
export const SET_COMMITS_HISTORY = "SET_COMMITS_HISTORY";

export type ACTIONS =
    typeof SET_ACTIVE_PATH |
    typeof SET_IS_ACTIVE_PATH_DIRECTORY |
    typeof SET_WORKSPACE |
    typeof SET_COMMITS_HISTORY;